server:
  port: 9000
spring:
  application:
    name: feign-consumer
  zipkin:
    base-url: http://localhost:9411/ #服务端地址
    sender:
      type: web  #数据传输方式，web表示以http报文的形式向服务端发送数据
  sleuth:
    sampler:
      probability: 1.0 #收集数据百分比，默认0.1（10%）
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

ribbon:
  ConnectTimeout: 50000
  ReadTimeout: 30000

  #对具体的feign client value里的服务设置超时时间
  #feign-provider:
  #  ribbon:
  #    ConnectTimeout: 5000
  #    ReadTimeout: 1000
  # MaxAutoRetryies: 1

feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
    response:
      enabled: true

hystrix:
  threadpool:
    default:
      coreSize: 15
      #-1时，SynchronousQueue(一手交钱一手交货) 否则LinkedBlockingQueue(无界队列)
      #设置最大队列大小
      maxQueueSize: 30
      #LinkedBlockingQueue的拒绝阈值
      queueSizeRejectionThreshold: 25
      # 最大线程池大小，此设置仅在您还设置allowMaximumSizeToDivergeFromCoreSize时才会生效
      maximumSize: 30
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
    #具体的commandKey  未生效?未找到原因！
    getVouchers:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000

ninja-provider-order-client:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    listOfServers: 127.0.0.3