server:
  port: 8081

spring:
  application:
    name: ninja-user
  #配置nacos注册中心地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        #group:  ninja-order
        cluster-name: SH
        ephemeral: false