server:
  port: 9001
spring:
  application:
    name: feign-provider
  zipkin:
    base-url: http://localhost:9411/ #服务端地址
    sender:
      type: web  #数据传输方式，web表示以http报文的形式向服务端发送数据
  sleuth:
    sampler:
      probability: 1.0 #收集数据百分比，默认0.1（10%）
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}



