zuul:
  routes:
    ninja-provider-order-client:
      service-id: ninja-provider-order-client
      path: /order/**
  ignored-services: '*'
#  prefix: /gw
#  strip-prefix: false
#  ignored-patterns: /**/queryOrdersByUserId/**




