spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learning_mysql?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      # 连接池配置
      #initial-size: 1  #初始化数量，如果配错密码直接启动报错，不配置这项，启动不会报错
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      # 监控配置
      web-stat-filter:
        enabled: true
        url-pattern: /druid/*
        exclusions: '/druid/login.html'
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: 123456
      # 配置 StatFilter 拦截器
      filters: stat,wall
  redis:
    host: 1.1.1.1
    port: 36379
    password: 123456
    timeout: 3000
    lettuce:
      pool:
        min-idle: 1
        max-active: 1
        max-idle: 1
        max-wait: 1
    jedis:
      pool:
        max-active: 1
        max-idle: 1
        max-wait: 1
        min-idle: 1

mybatis:
  #config-location: "classpath:mybatis/mybatis-config.xml"
  mapper-locations: "classpath*:mybatis/**/*.xml"
